name: CI CD Pipeline

on:
  push:
    branches: ["main"]

jobs:

  # ============================
  # 2) DEPLOYMENT JOB — RUNS AFTER CI SUCCESS
  # ============================
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 147.93.105.151
          username: mclanduser
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Starting deployment..."
            echo "After updating the SSH Private key"
            cd apps/TrueMeds
            git pull origin main
            npm install
            pm2 restart truemeds
